"""
Consistency Agent
Validates data integrity and consistency across the document using Gemini AI
"""
import json
from typing import Dict, Any, List
from dataclasses import asdict
from .base_agent import BaseAgent, Finding

# Optional AWS tracing for local development
try:
    from aws_lambda_powertools import Logger, Tracer
    logger = Logger()
    tracer = Tracer()
except:
    import logging
    logger = logging.getLogger(__name__)
    logging.basicConfig(level=logging.INFO)
    
    class MockTracer:
        def capture_method(self, func):
            return func
    tracer = MockTracer()


class ConsistencyAgent(BaseAgent):
    """
    Agent that checks for internal consistency in documents using Gemini AI.
    All analysis is performed by Gemini - no hardcoded findings.
    """
    
    def __init__(self, mcp_hub):
        super().__init__("Consistency Agent", mcp_hub)
    
    def has_relevant_content(self, document_data: Dict[str, Any]) -> bool:
        """Check if document has content relevant for consistency analysis"""
        text_content = self.extract_text_content(document_data)
        
        if not text_content or len(text_content.strip()) < 100:
            logger.info(f"[{self.agent_name}] No relevant content - document too short")
            return False
        
        # Check for numerical data or tables
        has_tables = bool(document_data.get('tables'))
        has_numbers = any(char.isdigit() for char in text_content)
        has_substantial_content = len(text_content.split()) > 50
        
        is_relevant = has_tables or has_numbers or has_substantial_content
        logger.info(f"[{self.agent_name}] Content relevance check: {is_relevant} (tables: {has_tables}, numbers: {has_numbers})")
        return is_relevant
    
    @tracer.capture_method
    def analyze(self, document_data: Dict[str, Any], 
               context: Dict[str, Any],
               previous_results: Dict[str, Any] = None) -> Dict[str, Any]:
        """
        Perform consistency analysis using Gemini AI.
        All findings are generated by Gemini based on actual document content.
        """
        logger.info(f"[{self.agent_name}] Starting Gemini-powered consistency analysis")
        
        text_content = self.extract_text_content(document_data)
        tables = document_data.get('tables', [])
        
        if not text_content or len(text_content.strip()) < 50:
            logger.info(f"[{self.agent_name}] Insufficient content for analysis")
            return self._empty_result("Insufficient document content for consistency analysis")
        
        # Use Gemini for comprehensive consistency analysis
        findings = self._gemini_consistency_analysis(text_content, tables)
        
        if not findings:
            logger.info(f"[{self.agent_name}] Gemini found no consistency issues")
            return self._empty_result("No consistency issues identified by Gemini analysis")
        
        confidence = self._calculate_confidence(findings)
        reasoning = self._generate_reasoning(findings)
        
        logger.info(f"[{self.agent_name}] Analysis complete: {len(findings)} findings")
        
        return {
            'agent_type': 'consistency',
            'success': True,
            'findings': [asdict(f) for f in findings],
            'confidence': confidence,
            'reasoning': reasoning,
            'metadata': {
                'analysis_method': 'gemini_ai',
                'checks_performed': 1,
                'issues_found': len([f for f in findings if f.severity in ['CRITICAL', 'HIGH']])
            }
        }
    
    def _gemini_consistency_analysis(self, text_content: str, tables: List[Dict]) -> List[Finding]:
        """
        Use Gemini AI for comprehensive consistency analysis.
        This is the PRIMARY analysis method - no hardcoded rules.
        """
        findings = []
        
        # Prepare table data for analysis
        table_text = ""
        if tables:
            for i, table in enumerate(tables):
                table_text += f"\nTable {i+1}:\n"
                for row in table.get('data', []):
                    table_text += " | ".join(str(cell) for cell in row) + "\n"
        
        # Truncate content if too long
        max_content_length = 5000
        if len(text_content) > max_content_length:
            text_content = text_content[:max_content_length] + "\n[Document truncated]"
        
        prompt = f"""You are an expert data analyst checking for internal consistency in documents.

IMPORTANT INSTRUCTIONS:
1. ONLY report inconsistencies that are ACTUALLY present in the document
2. DO NOT generate generic or hypothetical findings
3. Each finding must reference SPECIFIC contradictions or mismatches in the document
4. If the document is internally consistent, return an empty array

Document text:
---
{text_content}
---
{f"Tables in document:{table_text}" if table_text else "No tables in document."}

Analyze for:
1. Contradictory statements (e.g., different values for the same metric)
2. Numerical inconsistencies (e.g., totals that don't add up)
3. Date/timeline conflicts
4. Conflicting claims or assertions
5. Table calculation errors

For each SPECIFIC inconsistency found, provide:
- title: A specific, descriptive title
- description: Detailed explanation with SPECIFIC references to the conflicting data
- severity: "CRITICAL", "HIGH", or "MEDIUM"
- evidence: The exact conflicting values or statements from the document
- recommendation: How to resolve the inconsistency

Respond ONLY in this JSON format:
{{
  "consistency_issues": [
    {{
      "title": "...",
      "description": "...",
      "severity": "CRITICAL|HIGH|MEDIUM",
      "evidence": ["statement 1", "conflicting statement 2"],
      "recommendation": "..."
    }}
  ]
}}

If no specific inconsistencies are found, respond with:
{{
  "consistency_issues": []
}}
"""
        
        try:
            logger.info(f"[{self.agent_name}] Calling Gemini API for consistency analysis")
            response = self.invoke_llm(prompt)
            logger.info(f"[{self.agent_name}] Gemini response received, parsing...")
            
            # Parse JSON response
            start_idx = response.find('{')
            end_idx = response.rfind('}') + 1
            
            if start_idx != -1 and end_idx > start_idx:
                json_str = response[start_idx:end_idx]
                data = json.loads(json_str)
                
                issues = data.get('consistency_issues', [])
                logger.info(f"[{self.agent_name}] Gemini identified {len(issues)} consistency issues")
                
                for issue in issues:
                    # Validate that the issue has actual content
                    if not issue.get('description') or len(issue.get('description', '')) < 20:
                        logger.warning(f"[{self.agent_name}] Skipping vague finding: {issue.get('title', 'Unknown')}")
                        continue
                    
                    evidence = issue.get('evidence', [])
                    if isinstance(evidence, str):
                        evidence = [evidence]
                    
                    findings.append(self.create_finding(
                        severity=issue.get('severity', 'MEDIUM'),
                        category='consistency',
                        title=issue.get('title', 'Consistency Issue'),
                        description=issue.get('description', ''),
                        evidence=evidence if evidence else ['Identified through Gemini AI analysis'],
                        confidence=0.85,
                        recommendations=[issue.get('recommendation', 'Review and resolve inconsistency')]
                    ))
            else:
                logger.warning(f"[{self.agent_name}] Could not parse JSON from Gemini response")
        
        except json.JSONDecodeError as e:
            logger.error(f"[{self.agent_name}] JSON parsing error: {e}")
        except Exception as e:
            logger.error(f"[{self.agent_name}] Error in Gemini consistency analysis: {e}")
        
        return findings
    
    def _calculate_confidence(self, findings: List[Finding]) -> float:
        """Calculate overall confidence in consistency analysis"""
        if not findings:
            return 0.95
        
        critical_count = len([f for f in findings if f.severity == 'CRITICAL'])
        high_count = len([f for f in findings if f.severity == 'HIGH'])
        
        confidence = 0.95 - (critical_count * 0.15) - (high_count * 0.10)
        return max(0.0, min(1.0, confidence))
    
    def _generate_reasoning(self, findings: List[Finding]) -> str:
        """Generate human-readable reasoning"""
        if not findings:
            return "Gemini AI analysis found no internal inconsistencies in the document."
        
        critical = len([f for f in findings if f.severity == 'CRITICAL'])
        high = len([f for f in findings if f.severity == 'HIGH'])
        
        return (f"Gemini AI consistency analysis identified {len(findings)} issue(s): "
                f"{critical} critical, {high} high priority.")
    
    def _empty_result(self, reason: str) -> Dict[str, Any]:
        """Return empty result when no analysis can be performed"""
        return {
            'agent_type': 'consistency',
            'success': True,
            'findings': [],
            'confidence': 0.95,
            'reasoning': reason,
            'metadata': {
                'analysis_method': 'skipped',
                'checks_performed': 0,
                'issues_found': 0
            }
        }
