"""
Greenwashing Detector Agent
Identifies unsubstantiated environmental, social, and governance (ESG) claims using Gemini AI
"""
import json
from typing import Dict, Any, List
from dataclasses import asdict
from .base_agent import BaseAgent, Finding

# Optional AWS tracing for local development
try:
    from aws_lambda_powertools import Logger, Tracer
    logger = Logger()
    tracer = Tracer()
except:
    import logging
    logger = logging.getLogger(__name__)
    logging.basicConfig(level=logging.INFO)
    
    class MockTracer:
        def capture_method(self, func):
            return func
    tracer = MockTracer()


class GreenwashingDetectorAgent(BaseAgent):
    """
    Agent that detects greenwashing - misleading environmental claims using Gemini AI.
    All analysis is performed by Gemini - no hardcoded findings.
    """
    
    # Keywords to check for relevance (not for hardcoded analysis)
    ESG_KEYWORDS = {
        'carbon neutral', 'net zero', 'carbon negative',
        'sustainable', 'eco-friendly', 'green', 'environmentally friendly',
        'climate positive', 'carbon offset', 'renewable',
        'recyclable', 'biodegradable', 'natural',
        'clean energy', 'zero emissions', 'carbon free',
        'esg', 'environmental', 'sustainability', 'climate'
    }
    
    def __init__(self, mcp_hub):
        super().__init__("Greenwashing Detector", mcp_hub)
    
    def has_relevant_content(self, document_data: Dict[str, Any]) -> bool:
        """Check if document has environmental/ESG claims to analyze"""
        text_content = self.extract_text_content(document_data).lower()
        
        if not text_content or len(text_content.strip()) < 50:
            logger.info(f"[{self.agent_name}] No relevant content - document too short")
            return False
        
        # Check if document contains any ESG-related keywords
        has_esg_content = any(keyword in text_content for keyword in self.ESG_KEYWORDS)
        
        logger.info(f"[{self.agent_name}] Content relevance check: {has_esg_content}")
        return has_esg_content
    
    @tracer.capture_method
    def analyze(self, document_data: Dict[str, Any], 
               context: Dict[str, Any],
               previous_results: Dict[str, Any] = None) -> Dict[str, Any]:
        """
        Detect greenwashing using Gemini AI.
        All findings are generated by Gemini based on actual document content.
        """
        logger.info(f"[{self.agent_name}] Starting Gemini-powered greenwashing detection")
        
        text_content = self.extract_text_content(document_data)
        
        if not text_content or len(text_content.strip()) < 50:
            logger.info(f"[{self.agent_name}] Insufficient content for analysis")
            return self._empty_result("Insufficient document content for greenwashing analysis")
        
        # Use Gemini for comprehensive greenwashing analysis
        findings = self._gemini_greenwashing_analysis(text_content)
        
        if not findings:
            logger.info(f"[{self.agent_name}] Gemini found no greenwashing issues")
            return self._empty_result("No greenwashing issues identified by Gemini analysis")
        
        confidence = self._calculate_confidence(findings)
        risk_level = self._calculate_risk_level(findings)
        reasoning = self._generate_reasoning(findings, risk_level)
        
        logger.info(f"[{self.agent_name}] Analysis complete: {len(findings)} findings, risk: {risk_level}")
        
        return {
            'agent_type': 'greenwashing',
            'success': True,
            'findings': [asdict(f) for f in findings],
            'confidence': confidence,
            'reasoning': reasoning,
            'metadata': {
                'analysis_method': 'gemini_ai',
                'unsubstantiated_claims': len(findings),
                'greenwashing_risk': risk_level
            }
        }
    
    def _gemini_greenwashing_analysis(self, text_content: str) -> List[Finding]:
        """
        Use Gemini AI for comprehensive greenwashing detection.
        This is the PRIMARY analysis method - no hardcoded rules.
        """
        findings = []
        
        # Truncate content if too long
        max_content_length = 6000
        if len(text_content) > max_content_length:
            text_content = text_content[:max_content_length] + "\n[Document truncated]"
        
        prompt = f"""You are an expert ESG analyst specializing in detecting greenwashing - misleading or unsubstantiated environmental claims.

IMPORTANT INSTRUCTIONS:
1. ONLY report greenwashing issues that are ACTUALLY present in the document
2. DO NOT generate generic or hypothetical findings
3. Each finding must reference SPECIFIC claims from the document that lack evidence
4. If all environmental claims are properly substantiated, return an empty array

Document to analyze:
---
{text_content}
---

Greenwashing indicators to look for:
1. Vague claims without specific metrics (e.g., "eco-friendly" without data)
2. Claims without third-party verification or certification
3. Selective disclosure (highlighting positives, hiding negatives)
4. Hidden trade-offs (one green aspect masking other environmental harms)
5. Irrelevant claims (true but unimportant environmental claims)
6. "Lesser of two evils" claims
7. False or misleading claims
8. Claims without timeline or baseline

For each SPECIFIC greenwashing issue found, provide:
- claim: The exact environmental claim from the document
- issue: Why this claim is problematic (be specific)
- severity: "CRITICAL" (false claim), "HIGH" (misleading), or "MEDIUM" (vague)
- evidence_missing: What evidence or substantiation is lacking
- recommendation: How to properly substantiate the claim

Respond ONLY in this JSON format:
{{
  "greenwashing_issues": [
    {{
      "claim": "exact quote from document",
      "issue": "specific explanation of the problem",
      "severity": "CRITICAL|HIGH|MEDIUM",
      "evidence_missing": "what substantiation is needed",
      "recommendation": "how to fix"
    }}
  ]
}}

If no greenwashing issues are found, respond with:
{{
  "greenwashing_issues": []
}}
"""
        
        try:
            logger.info(f"[{self.agent_name}] Calling Gemini API for greenwashing detection")
            response = self.invoke_llm(prompt)
            logger.info(f"[{self.agent_name}] Gemini response received, parsing...")
            
            # Parse JSON response
            start_idx = response.find('{')
            end_idx = response.rfind('}') + 1
            
            if start_idx != -1 and end_idx > start_idx:
                json_str = response[start_idx:end_idx]
                data = json.loads(json_str)
                
                issues = data.get('greenwashing_issues', [])
                logger.info(f"[{self.agent_name}] Gemini identified {len(issues)} greenwashing issues")
                
                for issue in issues:
                    # Validate that the issue has actual content
                    if not issue.get('claim') or len(issue.get('claim', '')) < 10:
                        logger.warning(f"[{self.agent_name}] Skipping finding without specific claim")
                        continue
                    
                    findings.append(self.create_finding(
                        severity=issue.get('severity', 'MEDIUM'),
                        category='esg',
                        title=f"Unsubstantiated Environmental Claim",
                        description=f"{issue.get('issue', '')}",
                        evidence=[
                            f"Claim: \"{issue.get('claim', '')}\"",
                            f"Missing: {issue.get('evidence_missing', 'Substantiation needed')}"
                        ],
                        confidence=0.80,
                        recommendations=[issue.get('recommendation', 'Provide substantiation for environmental claim')]
                    ))
            else:
                logger.warning(f"[{self.agent_name}] Could not parse JSON from Gemini response")
        
        except json.JSONDecodeError as e:
            logger.error(f"[{self.agent_name}] JSON parsing error: {e}")
        except Exception as e:
            logger.error(f"[{self.agent_name}] Error in Gemini greenwashing analysis: {e}")
        
        return findings
    
    def _calculate_confidence(self, findings: List[Finding]) -> float:
        """Calculate confidence in analysis"""
        if not findings:
            return 0.95
        return 0.85
    
    def _calculate_risk_level(self, findings: List[Finding]) -> str:
        """Calculate overall greenwashing risk level"""
        if not findings:
            return 'LOW'
        
        high_severity = len([f for f in findings if f.severity in ['CRITICAL', 'HIGH']])
        
        if high_severity >= 3:
            return 'HIGH'
        elif high_severity >= 1:
            return 'MEDIUM'
        else:
            return 'LOW'
    
    def _generate_reasoning(self, findings: List[Finding], risk_level: str) -> str:
        """Generate reasoning summary"""
        if not findings:
            return "Gemini AI analysis found no greenwashing issues in the document."
        
        critical = len([f for f in findings if f.severity == 'CRITICAL'])
        high = len([f for f in findings if f.severity == 'HIGH'])
        
        return (f"Gemini AI greenwashing analysis identified {len(findings)} unsubstantiated claim(s): "
                f"{critical} critical, {high} high priority. Risk level: {risk_level}")
    
    def _empty_result(self, reason: str) -> Dict[str, Any]:
        """Return empty result when no analysis can be performed"""
        return {
            'agent_type': 'greenwashing',
            'success': True,
            'findings': [],
            'confidence': 0.95,
            'reasoning': reason,
            'metadata': {
                'analysis_method': 'skipped',
                'unsubstantiated_claims': 0,
                'greenwashing_risk': 'LOW'
            }
        }
