"""
Math Agent
Performs financial calculations, validates metrics, and analyzes quantitative data using Gemini AI
"""
import json
from typing import Dict, Any, List
from dataclasses import asdict
from .base_agent import BaseAgent, Finding

# Optional AWS tracing for local development
try:
    from aws_lambda_powertools import Logger, Tracer
    logger = Logger()
    tracer = Tracer()
except:
    import logging
    logger = logging.getLogger(__name__)
    logging.basicConfig(level=logging.INFO)
    
    class MockTracer:
        def capture_method(self, func):
            return func
    tracer = MockTracer()


class MathAgent(BaseAgent):
    """
    Agent that performs mathematical and financial analysis using Gemini AI.
    All analysis is performed by Gemini - no hardcoded findings.
    """
    
    def __init__(self, mcp_hub):
        super().__init__("Math Agent", mcp_hub)
    
    def has_relevant_content(self, document_data: Dict[str, Any]) -> bool:
        """Check if document has financial/mathematical content to analyze"""
        text_content = self.extract_text_content(document_data).lower()
        
        if not text_content or len(text_content.strip()) < 50:
            logger.info(f"[{self.agent_name}] No relevant content - document too short")
            return False
        
        # Check for financial/numerical indicators
        financial_keywords = [
            'revenue', 'profit', 'loss', 'income', 'expense', 'cost',
            'asset', 'liability', 'equity', 'cash', 'debt', 'capital',
            'margin', 'ratio', 'growth', 'return', 'yield', 'rate',
            'million', 'billion', 'thousand', '%', 'percent',
            'ebitda', 'roi', 'irr', 'npv', 'eps', 'p/e'
        ]
        
        has_financial_content = any(keyword in text_content for keyword in financial_keywords)
        has_numbers = any(char.isdigit() for char in text_content)
        has_tables = bool(document_data.get('tables'))
        
        is_relevant = has_financial_content and (has_numbers or has_tables)
        logger.info(f"[{self.agent_name}] Content relevance check: {is_relevant} (financial: {has_financial_content}, numbers: {has_numbers})")
        return is_relevant
    
    @tracer.capture_method
    def analyze(self, document_data: Dict[str, Any], 
               context: Dict[str, Any],
               previous_results: Dict[str, Any] = None) -> Dict[str, Any]:
        """
        Perform mathematical and financial analysis using Gemini AI.
        All findings are generated by Gemini based on actual document content.
        """
        logger.info(f"[{self.agent_name}] Starting Gemini-powered financial analysis")
        
        text_content = self.extract_text_content(document_data)
        tables = document_data.get('tables', [])
        
        if not text_content or len(text_content.strip()) < 50:
            logger.info(f"[{self.agent_name}] Insufficient content for analysis")
            return self._empty_result("Insufficient document content for financial analysis")
        
        # Use Gemini for comprehensive financial analysis
        findings = self._gemini_financial_analysis(text_content, tables)
        
        if not findings:
            logger.info(f"[{self.agent_name}] Gemini found no financial issues")
            return self._empty_result("No financial calculation issues identified by Gemini analysis")
        
        reasoning = self._generate_reasoning(findings)
        
        logger.info(f"[{self.agent_name}] Analysis complete: {len(findings)} findings")
        
        return {
            'agent_type': 'math',
            'success': True,
            'findings': [asdict(f) for f in findings],
            'confidence': 0.90,
            'reasoning': reasoning,
            'metadata': {
                'analysis_method': 'gemini_ai',
                'calculation_errors': len([f for f in findings if 'calculation' in f.category.lower()])
            }
        }
    
    def _gemini_financial_analysis(self, text_content: str, tables: List[Dict]) -> List[Finding]:
        """
        Use Gemini AI for comprehensive financial analysis.
        This is the PRIMARY analysis method - no hardcoded rules.
        """
        findings = []
        
        # Prepare table data for analysis
        table_text = ""
        if tables:
            for i, table in enumerate(tables):
                table_text += f"\nTable {i+1}:\n"
                for row in table.get('data', []):
                    table_text += " | ".join(str(cell) for cell in row) + "\n"
        
        # Truncate content if too long
        max_content_length = 5000
        if len(text_content) > max_content_length:
            text_content = text_content[:max_content_length] + "\n[Document truncated]"
        
        prompt = f"""You are an expert financial analyst and auditor. Analyze the following document for mathematical and financial issues.

IMPORTANT INSTRUCTIONS:
1. ONLY report issues that are ACTUALLY present in the document
2. DO NOT generate generic or hypothetical findings
3. Each finding must reference SPECIFIC numbers, calculations, or financial data from the document
4. If all calculations appear correct, return an empty array

Document text:
---
{text_content}
---
{f"Financial tables:{table_text}" if table_text else "No tables in document."}

Analyze for:
1. Calculation errors (totals that don't add up, incorrect percentages)
2. Financial ratio anomalies (unusual or concerning ratios)
3. Inconsistent financial figures (same metric with different values)
4. Missing or incomplete financial data
5. Unrealistic projections or growth rates
6. Balance sheet equation violations (Assets ≠ Liabilities + Equity)

For each SPECIFIC issue found, provide:
- title: A specific, descriptive title
- description: Detailed explanation with SPECIFIC numbers from the document
- severity: "CRITICAL" (major error), "HIGH" (significant concern), or "MEDIUM" (minor issue)
- evidence: The exact numbers or calculations that are problematic
- recommendation: How to correct the issue

Respond ONLY in this JSON format:
{{
  "financial_issues": [
    {{
      "title": "...",
      "description": "...",
      "severity": "CRITICAL|HIGH|MEDIUM",
      "evidence": ["specific number 1", "specific number 2"],
      "recommendation": "..."
    }}
  ]
}}

If no financial issues are found, respond with:
{{
  "financial_issues": []
}}
"""
        
        try:
            logger.info(f"[{self.agent_name}] Calling Gemini API for financial analysis")
            response = self.invoke_llm(prompt)
            logger.info(f"[{self.agent_name}] Gemini response received, parsing...")
            
            # Parse JSON response
            start_idx = response.find('{')
            end_idx = response.rfind('}') + 1
            
            if start_idx != -1 and end_idx > start_idx:
                json_str = response[start_idx:end_idx]
                data = json.loads(json_str)
                
                issues = data.get('financial_issues', [])
                logger.info(f"[{self.agent_name}] Gemini identified {len(issues)} financial issues")
                
                for issue in issues:
                    # Validate that the issue has actual content
                    if not issue.get('description') or len(issue.get('description', '')) < 20:
                        logger.warning(f"[{self.agent_name}] Skipping vague finding: {issue.get('title', 'Unknown')}")
                        continue
                    
                    evidence = issue.get('evidence', [])
                    if isinstance(evidence, str):
                        evidence = [evidence]
                    
                    findings.append(self.create_finding(
                        severity=issue.get('severity', 'MEDIUM'),
                        category='financial',
                        title=issue.get('title', 'Financial Issue'),
                        description=issue.get('description', ''),
                        evidence=evidence if evidence else ['Identified through Gemini AI analysis'],
                        confidence=0.85,
                        recommendations=[issue.get('recommendation', 'Review and verify calculation')]
                    ))
            else:
                logger.warning(f"[{self.agent_name}] Could not parse JSON from Gemini response")
        
        except json.JSONDecodeError as e:
            logger.error(f"[{self.agent_name}] JSON parsing error: {e}")
        except Exception as e:
            logger.error(f"[{self.agent_name}] Error in Gemini financial analysis: {e}")
        
        return findings
    
    def _generate_reasoning(self, findings: List[Finding]) -> str:
        """Generate reasoning summary"""
        if not findings:
            return "Gemini AI analysis found no financial calculation issues in the document."
        
        critical = len([f for f in findings if f.severity == 'CRITICAL'])
        high = len([f for f in findings if f.severity == 'HIGH'])
        
        return (f"Gemini AI financial analysis identified {len(findings)} issue(s): "
                f"{critical} critical, {high} high priority.")
    
    def _empty_result(self, reason: str) -> Dict[str, Any]:
        """Return empty result when no analysis can be performed"""
        return {
            'agent_type': 'math',
            'success': True,
            'findings': [],
            'confidence': 0.95,
            'reasoning': reason,
            'metadata': {
                'analysis_method': 'skipped',
                'calculation_errors': 0
            }
        }
