"""
Risk Analysis Agent
Performs comprehensive risk assessment across multiple dimensions using Gemini AI
"""
import json
from typing import Dict, Any, List, Optional
from dataclasses import asdict
from .base_agent import BaseAgent, Finding

# Optional AWS tracing for local development
try:
    from aws_lambda_powertools import Logger, Tracer
    logger = Logger()
    tracer = Tracer()
except:
    import logging
    logger = logging.getLogger(__name__)
    logging.basicConfig(level=logging.INFO)
    
    class MockTracer:
        def capture_method(self, func):
            return func
    tracer = MockTracer()


class RiskAnalysisAgent(BaseAgent):
    """
    Agent that performs comprehensive risk analysis using Gemini AI.
    All analysis is performed by Gemini - no hardcoded findings.
    """
    
    RISK_CATEGORIES = [
        'financial', 'operational', 'market', 'compliance',
        'reputational', 'strategic', 'technology', 'esg'
    ]
    
    def __init__(self, mcp_hub):
        super().__init__("Risk Analysis Agent", mcp_hub)
    
    def has_relevant_content(self, document_data: Dict[str, Any]) -> bool:
        """Risk analysis runs if document has substantial content"""
        text_content = self.extract_text_content(document_data)
        
        if not text_content or len(text_content.strip()) < 100:
            logger.info(f"[{self.agent_name}] No relevant content - document too short")
            return False
        
        # Risk agent runs on any substantial document
        has_substantial_content = len(text_content.split()) > 50
        
        logger.info(f"[{self.agent_name}] Content relevance check: {has_substantial_content}")
        return has_substantial_content
    
    @tracer.capture_method
    def analyze(self, document_data: Dict[str, Any], 
               context: Dict[str, Any],
               previous_results: Dict[str, Any] = None) -> Dict[str, Any]:
        """
        Perform comprehensive risk analysis using Gemini AI.
        All findings are generated by Gemini based on actual document content.
        """
        logger.info(f"[{self.agent_name}] Starting Gemini-powered risk analysis")
        
        text_content = self.extract_text_content(document_data)
        
        if not text_content or len(text_content.strip()) < 100:
            logger.info(f"[{self.agent_name}] Insufficient content for analysis")
            return self._empty_result("Insufficient document content for risk analysis")
        
        # Use Gemini for comprehensive risk analysis
        findings = self._gemini_risk_analysis(text_content, previous_results)
        
        if not findings:
            logger.info(f"[{self.agent_name}] Gemini found no significant risks")
            return self._empty_result("No significant risks identified by Gemini analysis")
        
        # Calculate risk scores by category
        risk_scores = self._calculate_risk_scores(findings)
        overall_risk = self._determine_overall_risk(risk_scores)
        reasoning = self._generate_reasoning(findings, risk_scores, overall_risk)
        
        logger.info(f"[{self.agent_name}] Analysis complete: {len(findings)} findings, overall risk: {overall_risk}")
        
        return {
            'agent_type': 'risk_analysis',
            'success': True,
            'findings': [asdict(f) for f in findings],
            'confidence': 0.85,
            'reasoning': reasoning,
            'metadata': {
                'analysis_method': 'gemini_ai',
                'risk_scores': risk_scores,
                'overall_risk_level': overall_risk,
                'total_risks': len(findings)
            }
        }
    
    def _gemini_risk_analysis(self, text_content: str, 
                             previous_results: Optional[Dict[str, Any]]) -> List[Finding]:
        """
        Use Gemini AI for comprehensive risk analysis.
        This is the PRIMARY analysis method - no hardcoded rules.
        """
        findings = []
        
        # Build context from previous agent results
        previous_context = ""
        if previous_results:
            previous_context = "\n\nPrevious agent findings summary:\n"
            for agent_type, result in previous_results.items():
                if isinstance(result, dict) and result.get('findings'):
                    finding_count = len(result.get('findings', []))
                    reasoning = result.get('reasoning', 'N/A')
                    previous_context += f"- {agent_type}: {finding_count} findings. {reasoning}\n"
        
        # Truncate content if too long
        max_content_length = 5000
        if len(text_content) > max_content_length:
            text_content = text_content[:max_content_length] + "\n[Document truncated]"
        
        prompt = f"""You are an expert risk analyst performing due diligence on an investment opportunity.

IMPORTANT INSTRUCTIONS:
1. ONLY report risks that are ACTUALLY evident from the document content
2. DO NOT generate generic or hypothetical risks
3. Each risk must reference SPECIFIC content, statements, or data from the document
4. If no significant risks are evident, return an empty array

Document to analyze:
---
{text_content}
---
{previous_context if previous_context else ""}

Analyze for risks across these categories:
- Financial Risk: Cash flow, debt, profitability concerns
- Operational Risk: Business operations, supply chain, capacity
- Market Risk: Competition, market conditions, pricing
- Compliance Risk: Regulatory, legal issues
- Strategic Risk: Business model, competitive position
- Technology Risk: Tech dependencies, cybersecurity
- ESG Risk: Environmental, social, governance concerns

For each SPECIFIC risk identified, provide:
- category: One of the risk categories above
- title: A specific, descriptive title
- description: Detailed explanation referencing SPECIFIC content from the document
- likelihood: "HIGH", "MEDIUM", or "LOW"
- impact: "HIGH", "MEDIUM", or "LOW"
- severity: Based on likelihood x impact - "CRITICAL", "HIGH", or "MEDIUM"
- evidence: Specific quotes or references from the document
- mitigation: Recommended actions to address the risk

Respond ONLY in this JSON format:
{{
  "risks": [
    {{
      "category": "...",
      "title": "...",
      "description": "...",
      "likelihood": "HIGH|MEDIUM|LOW",
      "impact": "HIGH|MEDIUM|LOW",
      "severity": "CRITICAL|HIGH|MEDIUM",
      "evidence": "specific quote or reference",
      "mitigation": "..."
    }}
  ]
}}

If no significant risks are found, respond with:
{{
  "risks": []
}}
"""
        
        try:
            logger.info(f"[{self.agent_name}] Calling Gemini API for risk analysis")
            response = self.invoke_llm(prompt)
            logger.info(f"[{self.agent_name}] Gemini response received, parsing...")
            
            # Parse JSON response
            start_idx = response.find('{')
            end_idx = response.rfind('}') + 1
            
            if start_idx != -1 and end_idx > start_idx:
                json_str = response[start_idx:end_idx]
                data = json.loads(json_str)
                
                risks = data.get('risks', [])
                logger.info(f"[{self.agent_name}] Gemini identified {len(risks)} risks")
                
                for risk in risks:
                    # Validate that the risk has actual content
                    if not risk.get('description') or len(risk.get('description', '')) < 20:
                        logger.warning(f"[{self.agent_name}] Skipping vague risk: {risk.get('title', 'Unknown')}")
                        continue
                    
                    findings.append(self.create_finding(
                        severity=risk.get('severity', 'MEDIUM'),
                        category=risk.get('category', 'general').lower(),
                        title=risk.get('title', 'Risk Identified'),
                        description=risk.get('description', ''),
                        evidence=[
                            f"Likelihood: {risk.get('likelihood', 'UNKNOWN')}",
                            f"Impact: {risk.get('impact', 'UNKNOWN')}",
                            f"Evidence: {risk.get('evidence', 'N/A')}"
                        ],
                        confidence=0.80,
                        recommendations=[risk.get('mitigation', 'Develop mitigation strategy')]
                    ))
            else:
                logger.warning(f"[{self.agent_name}] Could not parse JSON from Gemini response")
        
        except json.JSONDecodeError as e:
            logger.error(f"[{self.agent_name}] JSON parsing error: {e}")
        except Exception as e:
            logger.error(f"[{self.agent_name}] Error in Gemini risk analysis: {e}")
        
        return findings
    
    def _calculate_risk_scores(self, findings: List[Finding]) -> Dict[str, float]:
        """Calculate risk scores by category (0-100)"""
        scores = {}
        
        for category in self.RISK_CATEGORIES:
            category_findings = [f for f in findings if f.category == category]
            
            if not category_findings:
                scores[category] = 10.0  # Baseline low risk
                continue
            
            score = 10.0
            for finding in category_findings:
                if finding.severity == 'CRITICAL':
                    score += 30
                elif finding.severity == 'HIGH':
                    score += 20
                elif finding.severity == 'MEDIUM':
                    score += 10
            
            scores[category] = min(100.0, score)
        
        return scores
    
    def _determine_overall_risk(self, risk_scores: Dict[str, float]) -> str:
        """Determine overall risk level"""
        if not risk_scores:
            return 'LOW'
        
        max_score = max(risk_scores.values())
        avg_score = sum(risk_scores.values()) / len(risk_scores)
        
        if max_score >= 80:
            return 'CRITICAL'
        elif max_score >= 60 or avg_score >= 50:
            return 'HIGH'
        elif max_score >= 40 or avg_score >= 30:
            return 'MEDIUM'
        else:
            return 'LOW'
    
    def _generate_reasoning(self, findings: List[Finding], 
                           risk_scores: Dict[str, float],
                           overall_risk: str) -> str:
        """Generate reasoning summary"""
        if not findings:
            return "Gemini AI analysis found no significant risks in the document."
        
        critical = len([f for f in findings if f.severity == 'CRITICAL'])
        high = len([f for f in findings if f.severity == 'HIGH'])
        
        # Find highest risk categories
        top_categories = sorted(risk_scores.items(), key=lambda x: x[1], reverse=True)[:3]
        top_risks = ", ".join([f"{cat} ({score:.0f})" for cat, score in top_categories if score > 10])
        
        return (f"Gemini AI risk analysis identified {len(findings)} risk(s): "
                f"{critical} critical, {high} high priority. "
                f"Overall risk level: {overall_risk}. "
                f"Top risk areas: {top_risks if top_risks else 'None significant'}")
    
    def _empty_result(self, reason: str) -> Dict[str, Any]:
        """Return empty result when no analysis can be performed"""
        return {
            'agent_type': 'risk_analysis',
            'success': True,
            'findings': [],
            'confidence': 0.95,
            'reasoning': reason,
            'metadata': {
                'analysis_method': 'skipped',
                'risk_scores': {cat: 10.0 for cat in self.RISK_CATEGORIES},
                'overall_risk_level': 'LOW',
                'total_risks': 0
            }
        }
